name: polymer_and_dart
description: Sample app built with the polymer.dart package
dependencies:
  polymer: ">=0.10.0 <0.11.0"
transformers:
- polymer:
    entry_points: [web/begin/index.html,
                   web/step1/index.html,
                   web/step2/index.html,
                   web/step3/index.html,
                   web/step4/index.html,
                   web/step5/index.html,
                   web/end/index.html]
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
